apiVersion: v1
kind: Secret
metadata:
  name: servicecitoyen-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "servicecitoyen"
  SERVICE_TERRITORY_URL: "https://gateway.tsirylab.com/serviceterritoire"
  SERVICE_UPLOAD_URL: "https://gateway.tsirylab.com/serviceupload"
