###########################################################################
# ÉTAPE 1 – Build Vite
###########################################################################
FROM node:20-slim AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci --ignore-scripts && npm cache clean --force

COPY . .

{% for e in envs -%}
ARG {{ e.name }}
{% endfor %}
ARG VITE_PORT={{ vite_port }}

ENV \
{% for e in envs -%}
  {{ e.name }}=${{ e.name }} \
{% endfor %}
  VITE_PORT=${VITE_PORT}

RUN npm run build

###########################################################################
# ÉTAPE 2 – Image Nginx (non-root)
###########################################################################
FROM nginxinc/nginx-unprivileged:1.25-alpine AS runner
USER 101
WORKDIR /usr/share/nginx/html

COPY --from=builder --chown=101:101 /app/dist .

COPY nginx.conf /etc/nginx/conf.d/default.conf
ENV PORT=${VITE_PORT}
EXPOSE {{ vite_port }}

CMD ["nginx","-g","daemon off;"]