apiVersion: v1
kind: Secret
metadata:
  name: servicebiblio-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_DATABASE: "servicebiblio"
  UPLOAD_URL: "https://gateway.tsirylab.com/serviceupload"
