apiVersion: v1
kind: Secret
metadata:
  name: serviceressource-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USER: "${DB_USER}"
  DB_PASS: "${DB_PASS}"
  DB_NAME: "serviceressource"
