apiVersion: v1
kind: Service
metadata:
  name: serviceressource-service
  namespace: pnud-agvm
spec:
  type: NodePort
  selector:
    app: serviceressource
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30130
