apiVersion: v1
kind: Service
metadata:
  name: servicetest-service
  namespace: pnud-agvm
spec:
  type: NodePort
  selector:
    app: servicetest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30130
